In [1]:
import numpy as np

In [2]:
height=[1.250,2.548,4.254,5.268,2.048]

In [3]:
weight=[1.2,2.58,4.54,5.28,2.48]

In [8]:
np__weight=np.array(weight)
np__weight

array([1.2 , 2.58, 4.54, 5.28, 2.48])

In [9]:
np__height=np.array(height)
np__height

array([1.25 , 2.548, 4.254, 5.268, 2.048])

In [10]:
bmi=np__height/np__weight**2

In [11]:
print(bmi)

[0.86805556 0.3827895  0.20638864 0.1889635  0.33298647]


In [12]:
a=[1.0,1.2,1.3]

In [13]:
b=[1.4,1.5,1.6]

In [15]:
np__a=np.array(a)
print(np__a)

[1.  1.2 1.3]


In [18]:
np__b=np.array(b)
print(np__b)

[1.4 1.5 1.6]


In [20]:
bmi=np__a/np__b**3
print(bmi)

[0.51020408 0.44444444 0.390625  ]
